// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// include/nsl/AST/ASTNode.h
//
// `ASTNode` — abstract base of every concrete AST node kind in
// `nsl-ast` (data-model §1.1). Carries the runtime `NodeKind`
// discriminator and the `SourceRange` whose endpoints round-trip to
// the post-`#line` virtual file coordinates (Principle IV; FR-018).
//
// Construction invariant (`contracts/ast-stability.contract.md`
// Invariant 1): every concrete node MUST be constructed with a
// non-empty `SourceRange`. The base ctor is `protected` and takes
// `(NodeKind, SourceRange)`; the default ctor is `= delete`d so a
// subclass cannot accidentally elide the location.
//
// Polymorphism: `accept(ASTVisitor&)` is the double-dispatch entry
// point. The forward declaration below avoids a header cycle —
// `ASTVisitor` includes `ASTNode.h` via the per-node-kind headers,
// not the other way around.

#ifndef NSL_AST_ASTNODE_H
#define NSL_AST_ASTNODE_H

#include "nsl/AST/NodeKind.h"
#include "nsl/Basic/SourceLocation.h"

#include "llvm/ADT/StringRef.h"

#include <vector>

namespace nsl::ast {

class ASTVisitor;

/// A user-source identifier — a non-owning view into the originating
/// `Buffer` whose lifetime equals the compilation's `SourceManager`.
/// Cross-references between AST nodes (per data-model §6) hold an
/// `Identifier`, not an `ASTNode*`, which is what makes FR-031
/// trivially satisfiable: the printer never serializes a pointer.
using Identifier = llvm::StringRef;

/// A dotted scoped name (e.g., `inst.finish`, `ic.ready`). One-part
/// names are valid; multi-part names model parser-notes N6 (proc-
/// instance method access) and N7 (dotted-`func` def). `parts` is
/// always non-empty for a well-formed name.
struct ScopedName {
  std::vector<Identifier> parts;
};

/// Abstract root of the AST class hierarchy.
class ASTNode {
public:
  /// Default construction is forbidden — every node MUST carry a
  /// `SourceRange` per Invariant 1. Trying to default-construct a
  /// concrete node is a compile-time error.
  ASTNode() = delete;

  /// Virtual destructor — required because subclasses are owned via
  /// `std::unique_ptr<ASTNode>` at various points in the printer's
  /// generic walks. Out-of-line in `ASTNode.cpp` so the vtable has
  /// a single home.
  virtual ~ASTNode();

  // ASTNodes are not copyable / movable: ownership is via
  // std::unique_ptr<T>; relocating an AST node (and its children)
  // would invalidate any cached references. Sema and downstream
  // layers may read but never duplicate AST nodes.
  ASTNode(const ASTNode &) = delete;
  ASTNode &operator=(const ASTNode &) = delete;
  ASTNode(ASTNode &&) = delete;
  ASTNode &operator=(ASTNode &&) = delete;

  /// Runtime kind discriminator (closed set; one per `NodeKind.def`
  /// entry).
  [[nodiscard]] NodeKind kind() const noexcept { return kind_; }

  /// Source-locating range — first-token-start to last-token-end of
  /// the parsed construct (FR-018). Always valid in well-constructed
  /// nodes; the printer asserts this per Invariant 1.
  [[nodiscard]] SourceRange loc() const noexcept { return loc_; }

  /// Double-dispatch entry point for the visitor pattern. Each
  /// concrete subclass overrides to call the matching
  /// `visitor.visit(*this)` overload. The override is generated by
  /// the `NSL_AST_NODE_BOILERPLATE` macro in the per-kind header so
  /// the implementations cannot drift from the kind.
  ///
  /// `accept` is `const` because the M2 visitor surface is read-
  /// only — `Printer` is the sole consumer and never mutates the
  /// AST. M3 (Sema) introduces its own mutating walker (`Expr::
  /// setInferredType`) outside this hierarchy; if a future visitor
  /// needs mutation, a parallel `MutatingASTVisitor` will be
  /// added rather than relaxing const here.
  virtual void accept(ASTVisitor &visitor) const = 0;

protected:
  /// Construct the base. Subclasses pass their own `NodeKind` and
  /// the parsed `SourceRange`. The range MUST satisfy `isValid()`
  /// (Invariant 1) — checked at print time.
  ASTNode(NodeKind k, SourceRange r) noexcept : kind_(k), loc_(r) {}

private:
  NodeKind kind_;
  SourceRange loc_;
};

/// Per-node-kind header boilerplate.
///
/// Each concrete node header expands this once inside its `class`
/// body. It generates:
///   - the protected ctor forwarding `(NodeKind::NK_<Name>, range)`
///     to `ASTNode`;
///   - the public `static constexpr NodeKind kKind` for `isa<>`-
///     style checks (M3 Sema may add a `dyn_cast` helper);
///   - the `accept(ASTVisitor&)` override calling the matching
///     `visit(<Name>&)` on the visitor.
///
/// The macro MUST be invoked inside `public:` access. The trailing
/// declaration of `accept` is split out so each subclass's `.cpp`
/// can hold an out-of-line definition (anchored in `ASTNode.cpp` to
/// avoid bloating per-kind translation units).
#define NSL_AST_NODE_BOILERPLATE(NameTok)                                     \
public:                                                                       \
  static constexpr NodeKind kKind = NodeKind::NK_##NameTok;                   \
  void accept(::nsl::ast::ASTVisitor &visitor) const override;                \
  static bool classof(const ::nsl::ast::ASTNode *n) noexcept {                \
    return n->kind() == kKind;                                                \
  }

} // namespace nsl::ast

#endif // NSL_AST_ASTNODE_H
