#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""scripts/gen_textmate_fixtures.py — generate the T1 keyword
fixture corpus from `include/nsl/Lex/KeywordSet.def`.

Per `specs/009-t1-textmate-grammar/contracts/scope-test-format.contract.md`
§1.2: `all-keywords.nsl` is the only generated fixture (one
occurrence per `KeywordSet.def` row, plus an inline scope
assertion). Other category fixtures (`all-numbers.nsl`,
`all-operators.nsl`, `all-directives.nsl`,
`comments-and-strings.nsl`, `macro-references.nsl`) are
hand-authored because their coverage axes are not enumerated in
any single `.def` file.

Per Constitution Principle V (deterministic): given the same
input `KeywordSet.def`, this script produces byte-identical
output across runs. Source-order iteration mirrors the
`gen_keyword_fixtures.py` precedent.

Per Constitution Principle VIII (TDD): the fixture lands BEFORE
the grammar's keyword pattern emission (T016). Running
`vscode-tmgrammar-test` against this fixture with the T005
skeleton grammar will FAIL on every assertion — that's the
red-state observation Principle VIII requires.

**T009 state**: emits one keyword line per `KeywordSet.def` row
PLUS an inline `// <- <scope>` assertion comment per
`contracts/scope-test-format.contract.md` §1.1 / `data-model.md`
§1.2. The scope is determined by the `KEYWORD_CATEGORY` table
(imported from `gen_textmate_grammar.py`).

Usage:
  python3 scripts/gen_textmate_fixtures.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Late import the parser/coverage check from the sibling
# generator so the keyword-set source-of-truth invariant
# (KEYWORD_CATEGORY mirrors KeywordSet.def) is checked here too.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_textmate_grammar import (  # type: ignore[import-not-found]
    KEYWORD_SET_DEF,
    parse_keyword_set,
    check_coverage,
    KEYWORD_CATEGORY,
    SCOPE_FOR_CATEGORY,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_OUT = (
    REPO_ROOT / "test" / "tooling" / "textmate"
    / "fixtures" / "all-keywords.nsl"
)

SPDX_HEADER = (
    "// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception\n"
    "//\n"
    "// all-keywords.nsl — GENERATED by\n"
    "// scripts/gen_textmate_fixtures.py from\n"
    "// include/nsl/Lex/KeywordSet.def. Do not hand-edit;\n"
    "// regenerate via `python3 scripts/gen_textmate_fixtures.py`.\n"
    "//\n"
    "// One line per reserved keyword from `nsl_lang.ebnf §15`.\n"
    "// Each line places the keyword in column 1 followed by an\n"
    "// inline `// <- <scope>` assertion comment per\n"
    "// contracts/scope-test-format.contract.md §1.1 — the\n"
    "// vscode-tmgrammar-test runner reads the assertion against\n"
    "// the previous line.\n"
)

# vscode-tmgrammar-test requires a `// SYNTAX TEST "<scope-name>"`
# header on line 1 of every test file. See the runner's README
# (test/tooling/textmate/node_modules/vscode-tmgrammar-test/README.md
# §"Unit tests"). The header MUST be the literal first comment.
SYNTAX_TEST_HEADER = '// SYNTAX TEST "source.nsl"\n'


def render_fixture(spellings: list[str]) -> str:
    """Build the fixture text deterministically with embedded
    `// <- <scope>` assertions for the runner."""
    out: list[str] = [SYNTAX_TEST_HEADER]
    out.append(SPDX_HEADER)
    out.append("\n")  # blank line before keyword block
    for sp in spellings:
        cat = KEYWORD_CATEGORY[sp]
        scope = SCOPE_FOR_CATEGORY[cat]
        out.append(sp + "\n")
        # The `// <-` assertion form points at column 1 of the
        # PREVIOUS line. The leading `<` aligns with column 1; the
        # length of the assertion target equals the keyword's
        # spelling length minus 1 (the `<` itself counts as col 1).
        # Using just `// <-` is sufficient — the runner asserts the
        # scope at column 1 of the previous line.
        out.append(f"// <- {scope}\n")
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Generate to memory and diff against the committed "
             "fixture; exit non-zero if they differ.",
    )
    args = parser.parse_args(argv)

    spellings = parse_keyword_set(KEYWORD_SET_DEF)
    check_coverage(spellings)
    rendered = render_fixture(spellings)

    if args.check:
        committed = FIXTURE_OUT.read_text(encoding="utf-8") if FIXTURE_OUT.exists() else ""
        if rendered != committed:
            sys.stderr.write(
                f"[gen_textmate_fixtures] {FIXTURE_OUT} is stale.\n"
                f"  Run: python3 scripts/gen_textmate_fixtures.py\n"
                f"  Then commit the regenerated file.\n"
            )
            return 1
        return 0

    FIXTURE_OUT.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_OUT.write_text(rendered, encoding="utf-8")
    sys.stdout.write(
        f"[gen_textmate_fixtures] wrote {FIXTURE_OUT} "
        f"({len(spellings)} keyword lines + {len(spellings)} "
        f"scope assertions)\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
