#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""scripts/gen_textmate_fixtures.py — generate the T1 keyword
fixture corpus from `include/nsl/Lex/KeywordSet.def`.

Per `specs/009-t1-textmate-grammar/contracts/scope-test-format.contract.md`
§1.2: `all-keywords.nsl` is the only generated fixture (one
occurrence per `KeywordSet.def` row, plus an inline scope
assertion). Other category fixtures (`all-numbers.nsl`,
`all-operators.nsl`, `all-directives.nsl`,
`comments-and-strings.nsl`, `macro-references.nsl`) are
hand-authored because their coverage axes are not enumerated in
any single `.def` file.

Per Constitution Principle V (deterministic): given the same
input `KeywordSet.def`, this script produces byte-identical
output across runs. Source-order iteration mirrors the
`gen_keyword_fixtures.py` precedent.

Per Constitution Principle VIII (TDD): the fixture lands BEFORE
the grammar's keyword pattern emission (T016). Running
`vscode-tmgrammar-test` against this fixture with the T005
skeleton grammar will FAIL on every assertion — that's the
red-state observation Principle VIII requires.

**T006 skeleton state**: at this point in the milestone, the
fixture generator emits ONE LINE per keyword (the keyword in
isolation as the start of a placeholder NSL fragment) but no
inline scope assertions. T009 (Phase 3) extends this script to
emit the `// <- <scope>` assertion comments per
`contracts/scope-test-format.contract.md` §1.1.

Usage:
  python3 scripts/gen_textmate_fixtures.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Late import the parser/coverage check from the sibling
# generator so the keyword-set source-of-truth invariant
# (KEYWORD_CATEGORY mirrors KeywordSet.def) is checked here too.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_textmate_grammar import (  # type: ignore[import-not-found]
    KEYWORD_SET_DEF,
    parse_keyword_set,
    check_coverage,
    KEYWORD_CATEGORY,
    SCOPE_FOR_CATEGORY,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_OUT = (
    REPO_ROOT / "test" / "tooling" / "textmate"
    / "fixtures" / "all-keywords.nsl"
)

SPDX_HEADER = (
    "// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception\n"
    "//\n"
    "// all-keywords.nsl — GENERATED by\n"
    "// scripts/gen_textmate_fixtures.py from\n"
    "// include/nsl/Lex/KeywordSet.def. Do not hand-edit;\n"
    "// regenerate via `python3 scripts/gen_textmate_fixtures.py`.\n"
    "//\n"
    "// One line per reserved keyword from `nsl_lang.ebnf §15`.\n"
    "// Each line places the keyword in column 1 so the\n"
    "// scope-test runner's `// <- <scope>` assertion form\n"
    "// (per contracts/scope-test-format.contract.md §1.1)\n"
    "// targets it directly.\n"
    "//\n"
    "// **T006 skeleton state**: only keyword lines are emitted;\n"
    "// inline scope assertions land in T009 (Phase 3).\n"
)


def render_fixture(spellings: list[str]) -> str:
    """Build the fixture text deterministically."""
    out: list[str] = [SPDX_HEADER, ""]
    for sp in spellings:
        out.append(sp)
        # T009 will append a `// <- <scope>` assertion line here
        # per contracts/scope-test-format.contract.md §1.1.
        # T006 skeleton emits only the keyword line.
    out.append("")  # POSIX trailing newline
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Generate to memory and diff against the committed "
             "fixture; exit non-zero if they differ.",
    )
    args = parser.parse_args(argv)

    spellings = parse_keyword_set(KEYWORD_SET_DEF)
    check_coverage(spellings)
    rendered = render_fixture(spellings)

    if args.check:
        committed = FIXTURE_OUT.read_text(encoding="utf-8") if FIXTURE_OUT.exists() else ""
        if rendered != committed:
            sys.stderr.write(
                f"[gen_textmate_fixtures] {FIXTURE_OUT} is stale.\n"
                f"  Run: python3 scripts/gen_textmate_fixtures.py\n"
                f"  Then commit the regenerated file.\n"
            )
            return 1
        return 0

    FIXTURE_OUT.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_OUT.write_text(rendered, encoding="utf-8")
    sys.stdout.write(
        f"[gen_textmate_fixtures] wrote {FIXTURE_OUT} "
        f"(skeleton state: {len(spellings)} keyword lines, "
        f"0 assertions emitted; assertions added in T009)\n"
    )
    # Touch SCOPE_FOR_CATEGORY / KEYWORD_CATEGORY so static
    # analysers see them imported-and-referenced (they will be
    # fully consumed by T009).
    _ = SCOPE_FOR_CATEGORY, KEYWORD_CATEGORY
    return 0


if __name__ == "__main__":
    sys.exit(main())
